import test from 'node:test';
import assert from 'node:assert/strict';
import { chmod, mkdir, mkdtemp, readFile, realpath, rm, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { inspectProject } from '../packages/inspection/index.js';
import { createBuildPlan, scanToolchains } from '../packages/engines/index.js';
import type { BuildOptions, ProjectInspection } from '../packages/domain/index.js';

async function tempDir(t: { after: (fn: () => void | Promise<void>) => void }, prefix: string): Promise<string> {
  const dir = await mkdtemp(join(tmpdir(), prefix));
  t.after(() => rm(dir, { recursive: true, force: true }));
  return dir;
}

async function write(root: string, rel: string, contents: string): Promise<void> {
  const target = join(root, rel);
  await mkdir(join(target, '..'), { recursive: true });
  await writeFile(target, contents, 'utf8');
}

const godotProject = `[application]
config/name="Harbor"
config/features=PackedStringArray("4.3", "Forward Plus")
`;

const godotPresets = `[preset.0]
name="Android"
platform="Android"
[preset.0.options]
package/unique_name="com.harbor.game"
[preset.1]
name="Linux"
platform="Linux"
`;

test('inspects Godot, Unity, Unreal, Android and iOS from real project files', async (t) => {
  const root = await tempDir(t, 'appops-inspect-');

  const godot = join(root, 'godot');
  await write(godot, 'project.godot', godotProject);
  await write(godot, 'export_presets.cfg', godotPresets);
  const godotInfo = await inspectProject(godot);
  assert.equal(godotInfo.engine, 'godot');
  assert.equal(godotInfo.name, 'Harbor');
  assert.equal(godotInfo.engineVersion, '4.3');
  assert.equal(godotInfo.appIdentifier, 'com.harbor.game');
  assert.deepEqual(godotInfo.targets.sort(), ['android', 'linux']);
  assert.equal(godotInfo.rootPath, await realpath(godot));

  const unity = join(root, 'unity');
  await write(unity, 'ProjectSettings/ProjectVersion.txt', 'm_EditorVersion: 2022.3.21f1\n');
  await write(unity, 'ProjectSettings/ProjectSettings.asset', '  productName: Harbor Unity\napplicationIdentifier: com.harbor.unity\n');
  await write(unity, 'Assets/Main.unity', '');
  await write(unity, 'Packages/manifest.json', '{}\n');
  const unityInfo = await inspectProject(unity);
  assert.equal(unityInfo.engine, 'unity');
  assert.equal(unityInfo.engineVersion, '2022.3.21f1');
  assert.equal(unityInfo.appIdentifier, 'com.harbor.unity');

  const unreal = join(root, 'unreal');
  await write(unreal, 'Harbor.uproject', '{"FileVersion":3,"EngineAssociation":"5.4"}\n');
  await write(unreal, 'Config/DefaultEngine.ini', '[/Script/AndroidRuntimeSettings.AndroidRuntimeSettings]\nPackageName=com.harbor.unreal\n');
  await write(unreal, 'Content/Main.umap', '');
  const unrealInfo = await inspectProject(unreal);
  assert.equal(unrealInfo.engine, 'unreal');
  assert.equal(unrealInfo.engineVersion, '5.4');
  assert.equal(unrealInfo.appIdentifier, 'com.harbor.unreal');

  const android = join(root, 'android');
  await write(android, 'gradlew', '#!/bin/sh\necho SHOULD_NOT_RUN\nexit 99\n');
  await chmod(join(android, 'gradlew'), 0o755);
  await write(android, 'settings.gradle', "include ':app'\n");
  await write(android, 'app/build.gradle', 'android { defaultConfig { applicationId "com.harbor.android" } }\n');
  await write(android, 'app/src/main/AndroidManifest.xml', '<manifest package="com.harbor.android" android:label="Harbor"></manifest>\n');
  const androidInfo = await inspectProject(android);
  assert.equal(androidInfo.engine, 'android');
  assert.equal(androidInfo.appIdentifier, 'com.harbor.android');
  assert.deepEqual(androidInfo.targets, ['android']);

  const ios = join(root, 'ios');
  await write(ios, 'Harbor.xcodeproj/project.pbxproj', 'PRODUCT_BUNDLE_IDENTIFIER = com.harbor.ios;\n');
  await write(ios, 'Harbor.xcodeproj/xcshareddata/xcschemes/Harbor.xcscheme', '<Scheme></Scheme>\n');
  const iosInfo = await inspectProject(ios);
  assert.equal(iosInfo.engine, 'ios');
  assert.equal(iosInfo.appIdentifier, 'com.harbor.ios');
  if (process.platform !== 'darwin') {
    assert.ok(iosInfo.findings.some((f) => f.code === 'ios.requires_macos'));
  }
});

test('Unity exported Gradle is not classified as native Android', async (t) => {
  const root = await tempDir(t, 'appops-unity-export-');
  await write(root, 'gradlew', '#!/bin/sh\nexit 0\n');
  await write(root, 'settings.gradle', "include ':unityLibrary'\ninclude ':launcher'\n");
  await write(root, 'unityLibrary/build.gradle', 'dependencies { implementation "com.unity3d.player:unity" }\n');
  await write(root, 'launcher/src/main/AndroidManifest.xml', '<manifest package="com.unity.export"></manifest>\n');
  await write(root, 'build.gradle', '// GENERATED BY UNITY\napply plugin: "com.android.application"\n');
  const info = await inspectProject(root);
  assert.equal(info.engine, 'unity');
  assert.ok(info.findings.some((f) => f.code === 'unity.exported_project'));
  assert.equal(info.findings.some((f) => f.code === 'detect.conflict' && /android/.test(f.message)), false);
});

test('Unity editor project with Gradle files stays Unity, Godot with android/build stays Godot', async (t) => {
  const root = await tempDir(t, 'appops-hosted-gradle-');
  const unity = join(root, 'unity-src');
  await write(unity, 'ProjectSettings/ProjectVersion.txt', 'm_EditorVersion: 6000.0.0f1\n');
  await write(unity, 'ProjectSettings/ProjectSettings.asset', '  productName: Mix\napplicationIdentifier: com.mix.unity\n');
  await write(unity, 'Assets/A.txt', 'ok');
  await write(unity, 'gradlew', '#!/bin/sh\nexit 0\n');
  await write(unity, 'settings.gradle', "include ':app'\n");
  await write(unity, 'app/src/main/AndroidManifest.xml', '<manifest></manifest>\n');
  const unityInfo = await inspectProject(unity);
  assert.equal(unityInfo.engine, 'unity');

  const godot = join(root, 'godot-src');
  await write(godot, 'project.godot', godotProject);
  await write(godot, 'export_presets.cfg', godotPresets);
  await write(godot, 'android/build/gradlew', '#!/bin/sh\nexit 0\n');
  await write(godot, 'android/build/build.gradle', 'apply plugin: "com.android.application"\n');
  const godotInfo = await inspectProject(godot);
  assert.equal(godotInfo.engine, 'godot');
});

test('mixed engine markers record a conflict and do not execute project scripts', async (t) => {
  const root = await tempDir(t, 'appops-mixed-');
  await write(root, 'project.godot', godotProject);
  await write(root, 'ProjectSettings/ProjectVersion.txt', 'm_EditorVersion: 2021.3.0f1\n');
  await write(root, 'ProjectSettings/ProjectSettings.asset', '  productName: Mixed\n');
  await write(root, 'gradlew', '#!/bin/sh\necho RAN > ran.txt\nexit 0\n');
  await chmod(join(root, 'gradlew'), 0o755);
  const info = await inspectProject(root);
  assert.equal(info.engine, 'godot');
  assert.ok(info.findings.some((f) => f.code === 'detect.conflict'));
  await assert.rejects(readFile(join(root, 'ran.txt')));
});

test('unknown folders and missing export presets become actionable findings', async (t) => {
  const root = await tempDir(t, 'appops-unknown-');
  const empty = join(root, 'empty');
  await mkdir(empty);
  const unknown = await inspectProject(empty);
  assert.equal(unknown.engine, 'unknown');
  assert.ok(unknown.findings.some((f) => f.code === 'detect.unknown'));

  const godot = join(root, 'godot-bare');
  await write(godot, 'project.godot', godotProject);
  const missing = await inspectProject(godot);
  assert.ok(missing.findings.some((f) => f.code === 'godot.missing_export_presets' && f.severity === 'error'));
  assert.ok(missing.findings.some((f) => f.fixHint));
});

test('scanToolchains lists official tools and does not fake availability', async () => {
  const tools = await scanToolchains();
  const names = tools.map((t) => t.name);
  for (const required of ['godot', 'unity', 'unreal-uat', 'java', 'android-sdk', 'xcodebuild']) {
    assert.ok(names.includes(required), `missing toolchain ${required}`);
  }
  const xcode = tools.find((t) => t.name === 'xcodebuild')!;
  if (process.platform !== 'darwin') {
    assert.equal(xcode.available, false);
    assert.match(xcode.reason ?? '', /macOS/);
  }
  for (const tool of tools) {
    if (tool.available) assert.ok(tool.executable);
    else assert.equal(tool.available, false);
  }
});

// Provisions validated APPOPS_* tool directories in tmp (outside HOME) so the
// planner emits real commands. These are directory/layout fixtures plus a fake
// version responders used only to test planner contracts — no real JDK/SDK/engine.
async function provisionTools(t: { after: (fn: () => void | Promise<void>) => void }, root: string): Promise<{
  restore: () => void;
  engineRoot: string;
}> {
  const gradleTools = join(root, 'tools/gradle');
  await mkdir(join(gradleTools, 'wrapper/dists/gradle-8.7-bin'), { recursive: true });
  await writeFile(join(gradleTools, 'wrapper/dists/gradle-8.7-bin/.ok'), '');
  await mkdir(join(gradleTools, 'dependency-cache'), { recursive: true });

  const godotData = join(root, 'tools/godot-data');
  await mkdir(join(godotData, 'export_templates/4.3.stable'), { recursive: true });

  const javaHome = join(root, 'tools/jdk');
  await mkdir(join(javaHome, 'bin'), { recursive: true });
  await writeFile(join(javaHome, 'bin/java'), '#!/bin/sh\nprintf \'openjdk version "21.0.1"\\n\'\n', { mode: 0o755 });
  await writeFile(join(javaHome, 'bin/javac'), '#!/bin/sh\nprintf \'javac 21.0.1\\n\'\n', { mode: 0o755 });
  await chmod(join(javaHome, 'bin/java'), 0o755);

  const sdk = join(root, 'tools/android-sdk');
  await mkdir(join(sdk, 'platforms/android-34'), { recursive: true });
  await mkdir(join(sdk, 'build-tools/34.0.0'), { recursive: true });
  await write(sdk, 'platforms/android-34/android.jar', 'planner fixture');
  await write(sdk, 'build-tools/34.0.0/lib/apksigner.jar', 'planner fixture');
  await write(sdk, 'build-tools/34.0.0/aapt2', '#!/bin/sh\nprintf \'Android Asset Packaging Tool (aapt) 2.19\\n\'\n');
  await chmod(join(sdk, 'build-tools/34.0.0/aapt2'), 0o755);
  await write(sdk, 'platform-tools/adb', '#!/bin/sh\nprintf \'Android Debug Bridge version 1.0.41\\n\'\n');
  await chmod(join(sdk, 'platform-tools/adb'), 0o755);

  // A minimal Unreal engine layout so unrealEngineRoot validates.
  const engineRoot = join(root, 'tools/UnrealEngine');
  await mkdir(join(engineRoot, 'Engine/Build/BatchFiles'), { recursive: true });
  await mkdir(join(engineRoot, 'Engine/Binaries/DotNET'), { recursive: true });
  await writeFile(join(engineRoot, 'Engine/Build/BatchFiles/RunUAT.sh'), '#!/bin/sh\nexit 0\n', { mode: 0o755 });
  await chmod(join(engineRoot, 'Engine/Build/BatchFiles/RunUAT.sh'), 0o755);

  const prior = {
    APPOPS_GRADLE_TOOLS_DIR: process.env.APPOPS_GRADLE_TOOLS_DIR,
    APPOPS_GODOT_DATA_DIR: process.env.APPOPS_GODOT_DATA_DIR,
    APPOPS_JAVA_HOME: process.env.APPOPS_JAVA_HOME,
    APPOPS_ANDROID_SDK_ROOT: process.env.APPOPS_ANDROID_SDK_ROOT,
  };
  process.env.APPOPS_GRADLE_TOOLS_DIR = gradleTools;
  process.env.APPOPS_GODOT_DATA_DIR = godotData;
  process.env.APPOPS_JAVA_HOME = javaHome;
  process.env.APPOPS_ANDROID_SDK_ROOT = sdk;
  const restore = () => {
    for (const [k, v] of Object.entries(prior)) {
      if (v === undefined) delete process.env[k];
      else process.env[k] = v;
    }
  };
  t.after(restore);
  return { restore, engineRoot };
}

test('createBuildPlan requires provisioned toolchains and fails closed with actionable findings when missing', async (t) => {
  const root = await tempDir(t, 'appops-plan-missing-');
  // Ensure APPOPS_* are unset for this test.
  const saved = {
    g: process.env.APPOPS_GRADLE_TOOLS_DIR, d: process.env.APPOPS_GODOT_DATA_DIR,
    j: process.env.APPOPS_JAVA_HOME, s: process.env.APPOPS_ANDROID_SDK_ROOT,
    jh: process.env.JAVA_HOME, ah: process.env.ANDROID_HOME, asr: process.env.ANDROID_SDK_ROOT,
  };
  delete process.env.APPOPS_GRADLE_TOOLS_DIR; delete process.env.APPOPS_GODOT_DATA_DIR;
  delete process.env.APPOPS_JAVA_HOME; delete process.env.APPOPS_ANDROID_SDK_ROOT;
  delete process.env.JAVA_HOME; delete process.env.ANDROID_HOME; delete process.env.ANDROID_SDK_ROOT;
  t.after(() => {
    for (const [k, v] of Object.entries({
      APPOPS_GRADLE_TOOLS_DIR: saved.g, APPOPS_GODOT_DATA_DIR: saved.d, APPOPS_JAVA_HOME: saved.j,
      APPOPS_ANDROID_SDK_ROOT: saved.s, JAVA_HOME: saved.jh, ANDROID_HOME: saved.ah, ANDROID_SDK_ROOT: saved.asr,
    })) { if (v === undefined) delete process.env[k]; else process.env[k] = v; }
  });

  const godot = join(root, 'godot');
  await write(godot, 'project.godot', godotProject);
  await write(godot, 'export_presets.cfg', godotPresets);
  const godotPlan = await createBuildPlan(await inspectProject(godot), { target: 'android', outputPath: join(root, 'out') });
  assert.equal(godotPlan.commands.length, 0);
  assert.ok(godotPlan.findings.some((f) => f.code === 'godot.missing_export_templates' && f.severity === 'error'));

  const android = join(root, 'android');
  await write(android, 'gradlew', '#!/bin/sh\nexit 0\n');
  await write(android, 'settings.gradle', "include ':app'\n");
  await write(android, 'app/build.gradle', 'android { defaultConfig { applicationId "com.h.a" } }\n');
  await write(android, 'app/src/main/AndroidManifest.xml', '<manifest package="com.h.a"></manifest>\n');
  const androidPlan = await createBuildPlan(await inspectProject(android), { target: 'android', outputPath: join(root, 'aab') });
  assert.equal(androidPlan.commands.length, 0);
  assert.ok(androidPlan.findings.some((f) => f.code === 'android.missing_gradle_cache'));
  assert.ok(androidPlan.findings.some((f) => f.code === 'android.missing_java' || f.code === 'android.missing_sdk'));
});

test('createBuildPlan uses official CLI argument arrays and mounts validated tool roots', async (t) => {
  const root = await tempDir(t, 'appops-plan-');
  await provisionTools(t, root);

  const godot = join(root, 'godot');
  await write(godot, 'project.godot', godotProject);
  await write(godot, 'export_presets.cfg', godotPresets);
  const inspection = await inspectProject(godot);
  const options: BuildOptions = { target: 'android', outputPath: join(root, 'out') };
  const plan = await createBuildPlan(inspection, options);
  assert.equal(plan.commands.length, 1);
  assert.deepEqual(plan.commands[0].args.slice(0, 3), ['--headless', '--path', inspection.rootPath]);
  assert.equal(plan.commands[0].args[3], '--export-release');
  assert.equal(plan.commands[0].args[4], 'Android');
  assert.ok(plan.commands[0].args[5].endsWith('.apk'));
  // Godot data dir surfaces to the runner via env for the per-run template link.
  assert.equal(plan.commands[0].env?.GODOT_TEMPLATES_SOURCE, process.env.APPOPS_GODOT_DATA_DIR);
  assert.ok(plan.commands[0].env?.XDG_DATA_HOME?.startsWith(join(root, 'out')));

  const noPreset = await createBuildPlan(inspection, { target: 'ios', outputPath: join(root, 'out-ios') });
  assert.equal(noPreset.commands.length, 0);
  assert.ok(noPreset.findings.some((f) => f.code === 'godot.missing_preset_for_target'));

  const android = join(root, 'android');
  await write(android, 'gradlew', '#!/bin/sh\nexit 0\n');
  await write(android, 'settings.gradle', "include ':app'\n");
  await write(android, 'app/build.gradle', 'android { defaultConfig { applicationId "com.harbor.android" } }\n');
  await write(android, 'app/src/main/AndroidManifest.xml', '<manifest package="com.harbor.android"></manifest>\n');
  const androidPlan = await createBuildPlan(await inspectProject(android), { target: 'android', outputPath: join(root, 'aab') });
  assert.equal(androidPlan.commands[0].executable, join(androidPlan.sourcePath, 'gradlew'));
  // Offline, no-daemon, task — the wrapper cannot download in the sandbox.
  assert.deepEqual(androidPlan.commands[0].args, ['--offline', '--no-daemon', 'app:bundleRelease']);
  assert.ok(androidPlan.expectedArtifacts[0].endsWith('.aab'));
  assert.equal(androidPlan.commands[0].env?.JAVA_HOME, process.env.APPOPS_JAVA_HOME);
  assert.equal(androidPlan.commands[0].env?.ANDROID_HOME, process.env.APPOPS_ANDROID_SDK_ROOT);
  assert.ok(androidPlan.commands[0].env?.GRADLE_USER_HOME?.startsWith(join(root, 'aab')));
  assert.ok(androidPlan.commands[0].env?.GRADLE_RO_DEP_CACHE?.includes('dependency-cache'));

  const unity = join(root, 'unity');
  await write(unity, 'ProjectSettings/ProjectVersion.txt', 'm_EditorVersion: 6000.0.23f1\n');
  await write(unity, 'ProjectSettings/ProjectSettings.asset', '  productName: U\napplicationIdentifier: com.u.app\n');
  await write(unity, 'Assets/A.txt', 'a');
  const linuxPlan = await createBuildPlan(await inspectProject(unity), { target: 'linux', outputPath: join(root, 'uout') });
  assert.ok(linuxPlan.commands[0].args.includes('-batchmode'));
  assert.ok(linuxPlan.commands[0].args.includes('-buildLinux64Player'));
  const androidUnity = await createBuildPlan(await inspectProject(unity), { target: 'android', outputPath: join(root, 'uand') });
  assert.equal(androidUnity.commands.length, 0);
  assert.ok(androidUnity.findings.some((f) => f.code === 'unity.missing_build_profile'));

  const unreal = join(root, 'unreal');
  await write(unreal, 'Game.uproject', '{"FileVersion":3,"EngineAssociation":"5.4"}\n');
  await write(unreal, 'Content/A.uasset', '');
  const uatPlan = await createBuildPlan(await inspectProject(unreal), {
    target: 'linux', outputPath: join(root, 'ue-out'), configuration: 'Shipping',
    engineExecutable: join(root, 'tools/UnrealEngine/Engine/Build/BatchFiles/RunUAT.sh'),
  });
  assert.equal(uatPlan.commands.length, 1);
  assert.equal(uatPlan.commands[0].args[0], 'BuildCookRun');
  assert.ok(uatPlan.commands[0].args.some((a) => a.startsWith('-platform=Linux')));
  assert.ok(uatPlan.commands[0].args.includes('-build'));
  assert.ok(uatPlan.commands[0].args.includes('-cook'));
  assert.ok(uatPlan.commands[0].args.includes('-package'));
  // Validated engine root is mounted for UAT's sibling AutomationTool/Binaries.
  assert.equal(uatPlan.commands[0].env?.UE_ENGINE_ROOT, join(root, 'tools/UnrealEngine'));
});

test('Godot Android AAB extension follows the preset export_format', async (t) => {
  const root = await tempDir(t, 'appops-godot-aab-');
  await provisionTools(t, root);
  const godot = join(root, 'godot');
  await write(godot, 'project.godot', godotProject);
  await write(godot, 'export_presets.cfg', `[preset.0]
name="Android"
platform="Android"
[preset.0.options]
package/unique_name="com.harbor.game"
gradle_build/use_gradle_build=true
gradle_build/export_format=1
`);
  const plan = await createBuildPlan(await inspectProject(godot), { target: 'android', outputPath: join(root, 'out') });
  assert.equal(plan.commands.length, 1);
  assert.ok(plan.expectedArtifacts[0].endsWith('.aab'), `expected .aab, got ${plan.expectedArtifacts[0]}`);
});

test('Godot Linux non-embedded export attests the fresh .pck sidecar, embedded does not', async (t) => {
  const root = await tempDir(t, 'appops-godot-pck-');
  await provisionTools(t, root);
  const godot = join(root, 'godot');
  await write(godot, 'project.godot', godotProject);
  // Default Godot 4 Linux preset: no embed_pck -> data ships as a .pck sidecar.
  await write(godot, 'export_presets.cfg', `[preset.0]
name="Linux"
platform="Linux/X11"
runnable=true
export_path="game.x86_64"
[preset.0.options]
binary_format/embed_pck=false
`);
  const plan = await createBuildPlan(await inspectProject(godot), { target: 'linux', outputPath: join(root, 'out') });
  assert.equal(plan.commands.length, 1);
  assert.equal(plan.expectedArtifacts.length, 2, 'executable + .pck must both be expected');
  assert.ok(plan.expectedArtifacts.some((a) => a.endsWith('.pck')), 'fresh .pck must be attested');

  const embedded = join(root, 'godot-embed');
  await write(embedded, 'project.godot', godotProject);
  await write(embedded, 'export_presets.cfg', `[preset.0]
name="Linux"
platform="Linux/X11"
runnable=true
export_path="game.x86_64"
[preset.0.options]
binary_format/embed_pck=true
`);
  const embeddedPlan = await createBuildPlan(await inspectProject(embedded), { target: 'linux', outputPath: join(root, 'out2') });
  assert.equal(embeddedPlan.expectedArtifacts.length, 1, 'embedded pck has no sidecar to attest');
  assert.ok(!embeddedPlan.expectedArtifacts.some((a) => a.endsWith('.pck')));
});

test('Unreal plan without a validated engine root fails closed', async (t) => {
  const root = await tempDir(t, 'appops-ue-bad-');
  const unreal = join(root, 'unreal');
  await write(unreal, 'Game.uproject', '{"FileVersion":3}\n');
  // A lone RunUAT.sh with no surrounding engine tree must be rejected.
  const fakeUat = join(root, 'lonely/RunUAT.sh');
  await mkdir(join(root, 'lonely'), { recursive: true });
  await writeFile(fakeUat, '#!/bin/sh\nexit 0\n', { mode: 0o755 });
  await chmod(fakeUat, 0o755);
  const plan = await createBuildPlan(await inspectProject(unreal), { target: 'linux', outputPath: join(root, 'out'), engineExecutable: fakeUat });
  assert.equal(plan.commands.length, 0);
  assert.ok(plan.findings.some((f) => f.code === 'unreal.invalid_engine_root'));
});

test('createBuildPlan does not invent a successful command when the engine is unknown', async (t) => {
  const root = await tempDir(t, 'appops-unknown-plan-');
  await mkdir(root, { recursive: true });
  const project: ProjectInspection = {
    rootPath: root,
    name: 'none',
    engine: 'unknown',
    engineVersion: null,
    appIdentifier: null,
    targets: [],
    findings: [],
    inspectedAt: new Date().toISOString(),
  };
  const plan = await createBuildPlan(project, { target: 'linux', outputPath: join(root, 'out') });
  assert.equal(plan.commands.length, 0);
  assert.ok(plan.findings.some((f) => f.code === 'build.unknown_engine'));
});

test('inspectProject follows realpath and does not require git', async (t) => {
  const root = await tempDir(t, 'appops-realpath-');
  const actual = join(root, 'actual');
  await write(actual, 'project.godot', godotProject);
  await write(actual, 'export_presets.cfg', godotPresets);
  const link = join(root, 'link');
  await symlink(actual, link);
  const info = await inspectProject(link);
  assert.equal(info.engine, 'godot');
  assert.equal(info.rootPath, await realpath(actual));
});
